parts: Fixup! dc build issue
- Output:
packages/apps/XiaomiParts/DcDimming/src/com/android/dcdimming/DcDimmingSettingsActivity.java:33: merror: incompatible types: DcDimmingSettingsFragment cannot be converted to Fragment
                new DcDimmingSettingsFragment(), TAG_DCDIMMING).commit();
                m^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error